server:
  port: 8099
  servlet:
    contextPath: /department

datasource:
  department:
    url: jdbc:mysql://localhost:3306/department?useSSL=false
    username: alex
    password: ilovemyjob
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect